# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubert" do
  name "kubert"
  desc ""
  homepage "https://github.com/idebeijer/kubert"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubert"
  bash_completion "completions/kubert.bash"
  zsh_completion "completions/kubert.zsh"
  fish_completion "completions/kubert.fish"

  on_macos do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_darwin_amd64.tar.gz"
      sha256 "e46324817a534bea99ec984be9786643bf2b80bc5a158b88757803852b9eb70f"
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_darwin_arm64.tar.gz"
      sha256 "49b44f64691de131179160e95af1d03aec6f9e41be41bd89ca7ec05ad23b49ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_linux_amd64.tar.gz"
      sha256 "cfa850435ea0c9a481425818f7aae46faef3b54f5604d39d346fec7a9a2fd301"
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_linux_arm64.tar.gz"
      sha256 "c4c291133af88a8265e7dd5425298ec76dc6111ec646e96bafc454b4df226dd4"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubert"]
    end
  end

  # No zap stanza required
end
