# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubert" do
  name "kubert"
  desc ""
  homepage "https://github.com/idebeijer/kubert"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubert"
  bash_completion "completions/kubert.bash"
  zsh_completion "completions/kubert.zsh"
  fish_completion "completions/kubert.fish"

  on_macos do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_darwin_amd64.tar.gz"
      sha256 "3159b45effa4c9002e4ad4bbba183427ad8e3165ab9c454d0bb5bbeb9fb8544b"
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_darwin_arm64.tar.gz"
      sha256 "cd0bdea9be820121a20d5dd2e9d75fabf4ae1fda35db38a2ed73195f6fd477c1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_linux_amd64.tar.gz"
      sha256 "53a3153716f4f1e1c45505b0aca293ec545ebb31fbc51be3d49a29ca59b6adb8"
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_linux_arm64.tar.gz"
      sha256 "4974ecda98a246a9d3b78ae5d554d4437b1953d3ff482937730a9cc33f658aed"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubert"]
    end
  end

  # No zap stanza required
end
