# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubert" do
  name "kubert"
  desc ""
  homepage "https://github.com/idebeijer/kubert"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubert"
  bash_completion "completions/kubert.bash"
  zsh_completion "completions/kubert.zsh"
  fish_completion "completions/kubert.fish"

  on_macos do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_darwin_amd64.tar.gz"
      sha256 "f5990a496b6c3368d53b4cb2d7a277c788fb2b652b05808190f7dad257b2eb86"
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_darwin_arm64.tar.gz"
      sha256 "d707ba0db6b963821665fdbee15f89d9ede28888e582e8bec1e38e48a71b65bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_linux_amd64.tar.gz"
      sha256 "5cbff5e910482c8d4a589ed3ad52ee7631cea6ad3244124649c1bf9fa6ba8b06"
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v#{version}/kubert_#{version}_linux_arm64.tar.gz"
      sha256 "44b62525bf7df83578ab784cd8a8e4291bd6787c45b8b526e03fce8063d84a58"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubert"]
    end
  end

  # No zap stanza required
end
