# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubert < Formula
  desc ""
  homepage "https://github.com/idebeijer/kubert"
  version "0.0.2"

  depends_on "fzf" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v0.0.2/kubert_0.0.2_darwin_amd64.tar.gz"
      sha256 "c2a927119989b6ae7fba1b5f2d5e0cecf178e312119f6c9473bcaf20ba0859e8"

      def install
        bin.install "kubert"
        zsh_completion.install "completions/kubert.zsh" => "_kubert"
        bash_completion.install "completions/kubert.bash" => "kubert"
        fish_completion.install "completions/kubert.fish"
      end
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v0.0.2/kubert_0.0.2_darwin_arm64.tar.gz"
      sha256 "038e4c5dbe3edcb5abc2686c9c511303f64cb238518e045baeef226fcdfadd0a"

      def install
        bin.install "kubert"
        zsh_completion.install "completions/kubert.zsh" => "_kubert"
        bash_completion.install "completions/kubert.bash" => "kubert"
        fish_completion.install "completions/kubert.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idebeijer/kubert/releases/download/v0.0.2/kubert_0.0.2_linux_amd64.tar.gz"
        sha256 "b4236426c45b63384df9bbc76c0ccf66a44a2a69577b9d0a8b21722bea3eb933"

        def install
          bin.install "kubert"
          zsh_completion.install "completions/kubert.zsh" => "_kubert"
          bash_completion.install "completions/kubert.bash" => "kubert"
          fish_completion.install "completions/kubert.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idebeijer/kubert/releases/download/v0.0.2/kubert_0.0.2_linux_arm64.tar.gz"
        sha256 "e817de956b2dd02864ad697d55dc548b7ea9e59a9d9db2d7f87a033c0ede0a5a"

        def install
          bin.install "kubert"
          zsh_completion.install "completions/kubert.zsh" => "_kubert"
          bash_completion.install "completions/kubert.bash" => "kubert"
          fish_completion.install "completions/kubert.fish"
        end
      end
    end
  end
end
