# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubert < Formula
  desc ""
  homepage "https://github.com/idebeijer/kubert"
  version "0.0.1"

  depends_on "fzf" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    on_intel do
      url "https://github.com/idebeijer/kubert/releases/download/v0.0.1/kubert_0.0.1_darwin_amd64.tar.gz"
      sha256 "708b202c175740e5fd029da542e0700d47272b14767d94ed4a007cffb812db35"

      def install
        bin.install "kubert"
        zsh_completion.install "completions/kubert.zsh" => "_kubert"
        bash_completion.install "completions/kubert.bash" => "kubert"
        fish_completion.install "completions/kubert.fish"
      end
    end
    on_arm do
      url "https://github.com/idebeijer/kubert/releases/download/v0.0.1/kubert_0.0.1_darwin_arm64.tar.gz"
      sha256 "95cb3dc6f34bbde4306d0da1dd1073adcd352bc43b0caa482ea8ed0571aad882"

      def install
        bin.install "kubert"
        zsh_completion.install "completions/kubert.zsh" => "_kubert"
        bash_completion.install "completions/kubert.bash" => "kubert"
        fish_completion.install "completions/kubert.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idebeijer/kubert/releases/download/v0.0.1/kubert_0.0.1_linux_amd64.tar.gz"
        sha256 "2bf58c0d5bc184efb61dfab197c7301b65e765c3a0b18bc8669c5d5d88fe5957"

        def install
          bin.install "kubert"
          zsh_completion.install "completions/kubert.zsh" => "_kubert"
          bash_completion.install "completions/kubert.bash" => "kubert"
          fish_completion.install "completions/kubert.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idebeijer/kubert/releases/download/v0.0.1/kubert_0.0.1_linux_arm64.tar.gz"
        sha256 "a34a96e02e2d30dfaf62e26397a4a96ea27674603d712da380cb528ca55b0e2c"

        def install
          bin.install "kubert"
          zsh_completion.install "completions/kubert.zsh" => "_kubert"
          bash_completion.install "completions/kubert.bash" => "kubert"
          fish_completion.install "completions/kubert.fish"
        end
      end
    end
  end
end
